name: BFree Automation 🧪
 
on:
  push:
 
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name:  Run end-to-end tests on desktop viewport 💻
        uses: cypress-io/github-action@v2
        with:
          command: npm test